# Use the official MongoDB image
FROM mongo:latest

# Expose the default MongoDB port
EXPOSE 27017

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=username
ENV MONGO_INITDB_ROOT_PASSWORD=password

# Create necessary directories
RUN mkdir -p /data/db /data/db

# Set permissions
RUN chown -R mongodb:mongodb /data/db /data/db

# Start MongoDB
CMD ["mongod"]
